name: Test/build

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache location
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest Cython wheel

    - name: Build sdist
      run: |
        python setup.py sdist

    - name: Build wheel
      run: |
        python setup.py bdist_wheel

    - name: Install vpython
      run: |
        pip install .

    - name: Run tests
      run: |
        pytest vpython

    - name: Import test
      run: |
        python -c "import vpython"

  build_aarch64:

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [cp37-cp37m, cp38-cp38, cp39-cp39]
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.python-version }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64

    steps:

    - uses: actions/checkout@v1

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1

    - name: Install dependencies
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
           ${{ env.img }} \
           bash -exc '${{ env.py }} -m venv .env && \
           source .env/bin/activate && \
           python -m pip install --upgrade pip && \
           pip install pytest Cython wheel && \
           python setup.py bdist_wheel && \
           pip install . && \
           pytest vpython && \
           python -c "import vpython" && \
           deactivate'
